In [1]:
import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
from datasets import load_dataset

data_files = {"train": "data/split_dataset/train.csv", "test": "data/split_dataset/test.csv", "validation": "data/split_dataset/validate.csv"}
dataset = load_dataset("csv", data_files=data_files)

print(dataset["train"][0])

{'text': 'Stock market today Live updatesThe and the Nasdaq Composite slid on Thursday dragged lower by Nvidia sharesStock futures slipped on Friday after the latest producer price index data came in much hotter than expected adding sticky inflation to a list of concerns that has caused market turbulence this mont', 'label': 0, 'date': '2026-02-26', 'percentage_increase': -1.569168}

In [3]:
dataset["train"]

Dataset({
    features: ['text', 'label', 'date', 'percentage_increase'],
    num_rows: 1122
})

In [4]:
text_train = pd.read_csv("data/split_dataset/train.csv")
text_test = pd.read_csv("data/split_dataset/test.csv")
text_val = pd.read_csv("data/split_dataset/validate.csv")

In [5]:
text_train.head()

,text,label,date,percentage_increase
0,Stock market today Live updatesThe and the Nas...,0,2026-02-26,-1.569168
1,The Google Pixel a Is Barely Different From th...,1,2026-02-18,0.536858
2,The next iTunes may be vibe codedThis is Lowpa...,1,2026-02-19,0.121295
3,AMD's future Medusa Halo APUs could use LPDDR ...,0,2026-02-10,-0.874343
4,Meta will deploy standalone Nvidia Grace CPUs ...,1,2026-02-18,0.536858

In [6]:
text_test.head()

,text,label,date,percentage_increase
0,Berkshire CEO Greg Abel vows to keep Buffett's...,1,2026-02-28,2.391352
1,Today's NYT Mini Crossword Answers for Thursda...,0,2026-02-26,-1.569168
2,Microsoft gives Windows laggards the gift of t...,1,2026-02-24,1.081698
3,Apple launches lower cost iPhone and a new iPa...,1,2026-03-02,2.391352
4,Founder ditches AWS for Euro stack finds sover...,1,2026-02-20,1.079867

In [7]:
text_val.head()

,text,label,date,percentage_increase
0,US appears open to reversing some China tech b...,1,2026-02-16,0.667838
1,CNBC Daily Open. markets rise on tech rebound ...,0,2026-02-10,-0.874343
2,OpenAI Codex Spark Achieves Ultra Fast Coding ...,1,2026-03-02,2.391352
3,The latest Linux kernel release closes out the...,0,2026-02-10,-0.874343
4,Neuromorphic photonic computing with an electr...,1,2026-02-07,1.919107

In [8]:
# Initialize the BERT tokenizer
# set num_labels to 2 for binary classification (price increase vs no increase)
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert", num_labels=2, ignore_mismatched_sizes=True)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

In [9]:
print(model.config)

BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.2.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [10]:
# Tokenize a sample text
sample_text = "I absolutely loved this movie! Highly recommend it."
tokens = tokenizer(sample_text, padding="max_length", truncation=True, max_length=128)

print(tokens)

{'input_ids': [101, 1045, 7078, 3866, 2023, 3185, 999, 3811, 16755, 2009, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [11]:
# Tokenize the entire dataset
def tokenize_function(dataset):
    return tokenizer(dataset["text"], padding="max_length", truncation=True, max_length=128)

In [12]:
# Apply the tokenizer to the dataset
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Inspect tokenized samples
print(tokenized_datasets["train"][0])

{'text': 'Stock market today Live updatesThe and the Nasdaq Composite slid on Thursday dragged lower by Nvidia sharesStock futures slipped on Friday after the latest producer price index data came in much hotter than expected adding sticky inflation to a list of concerns that has caused market turbulence this mont', 'label': 0, 'date': '2026-02-26', 'percentage_increase': -1.569168, 'input_ids': [101, 4518, 3006, 2651, 2444, 14409, 10760, 1998, 1996, 17235, 2850, 4160, 12490, 4934, 2006, 9432, 7944, 2896, 2011, 1050, 17258, 2401, 6661, 14758, 17795, 5707, 2006, 5958, 2044, 1996, 6745, 3135, 3976, 5950, 2951, 2234, 1999, 2172, 22302, 2084, 3517, 5815, 15875, 14200, 2000, 1037, 2862, 1997, 5936, 2008, 2038, 3303, 3006, 29083, 2023, 18318, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [13]:
# Calculate class weights
from sklearn.utils.class_weight import compute_class_weight

labels = dataset["train"]["label"]
class_weights = compute_class_weight("balanced", classes=np.unique(labels), y=labels)
print(class_weights)

# adjust later

[1.56703911 0.73429319]

In [14]:
# Label mapping
label_mapping = {0: "price_decrease", 1: "price_increase"}
dataset = dataset.map(lambda x: {"label": label_mapping[x["label"]]})

# verify
print(dataset["train"][0])

{'text': 'Stock market today Live updatesThe and the Nasdaq Composite slid on Thursday dragged lower by Nvidia sharesStock futures slipped on Friday after the latest producer price index data came in much hotter than expected adding sticky inflation to a list of concerns that has caused market turbulence this mont', 'label': 'price_decrease', 'date': '2026-02-26', 'percentage_increase': -1.569168}

In [15]:
# might want to freeze some layers of the model to prevent overfitting on small dataset
# or modify the architecture to better suit the task (e.g. add regression head for predicting percentage increase instead of classification head)
# i'll come back to this after i get the data processing and training loop working

In [16]:
# Assigning hyperparameters

from transformers import TrainingArguments

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",             # Directory for saving model checkpoints
    eval_strategy="epoch",              # Evaluate at the end of each epoch
    learning_rate=5e-5,                 # Start with a small learning rate
    per_device_train_batch_size=16,     # Batch size per GPU
    per_device_eval_batch_size=16,
    num_train_epochs=3,                 # Number of epochs
    weight_decay=0.01,                  # Regularization
    save_total_limit=2,                 # Limit checkpoints to save space
    logging_dir="./logs",               # Directory for logs
    logging_steps=100,                  # Log every 100 steps
    fp16=True                           # Enable mixed precision for faster training
)

print(training_args)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=True,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./logs,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
neftune_noise_alpha=None,
num_train_epochs=3,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=./results,
parallelism_config=None,
per_device_eval_batch_size=16,
per_device_train_batch_size=16,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.STEPS,
save_total_limit=2,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_space_id=trackio,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.01,
)

In [17]:
# metrics

from transformers import Trainer
from evaluate import load

# Load a metric (F1-score in this case)
metric = load("f1")

# Define a custom compute_metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [18]:
# Data collation function to handle padding
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [20]:
trainer = Trainer(
    model=model,                        # Pre-trained BERT model
    args=training_args,                 # Training arguments
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    processing_class=tokenizer,
    data_collator=data_collator,        # Efficient batching
    compute_metrics=compute_metrics     # Custom metric
)

# Start training
trainer.train()

/Users/alexjun/projects/vgt_price_predicter/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt: